# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/AxRobotUtility.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1800, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1800, 800))
        MainWindow.setStatusTip("")
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(10)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lstwFunctionSelector = QtWidgets.QListWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstwFunctionSelector.sizePolicy().hasHeightForWidth())
        self.lstwFunctionSelector.setSizePolicy(sizePolicy)
        self.lstwFunctionSelector.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lstwFunctionSelector.setFont(font)
        self.lstwFunctionSelector.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lstwFunctionSelector.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lstwFunctionSelector.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.lstwFunctionSelector.setObjectName("lstwFunctionSelector")
        item = QtWidgets.QListWidgetItem()
        self.lstwFunctionSelector.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstwFunctionSelector.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstwFunctionSelector.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstwFunctionSelector.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstwFunctionSelector.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstwFunctionSelector.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lstwFunctionSelector.addItem(item)
        self.verticalLayout.addWidget(self.lstwFunctionSelector)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnRealTimeStatusExpandAll = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnRealTimeStatusExpandAll.setFont(font)
        self.btnRealTimeStatusExpandAll.setObjectName("btnRealTimeStatusExpandAll")
        self.horizontalLayout_4.addWidget(self.btnRealTimeStatusExpandAll)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.trwRealTimeStatus = QtWidgets.QTreeWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trwRealTimeStatus.sizePolicy().hasHeightForWidth())
        self.trwRealTimeStatus.setSizePolicy(sizePolicy)
        self.trwRealTimeStatus.setMinimumSize(QtCore.QSize(0, 0))
        self.trwRealTimeStatus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.trwRealTimeStatus.setFont(font)
        self.trwRealTimeStatus.setToolTip("")
        self.trwRealTimeStatus.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.trwRealTimeStatus.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.trwRealTimeStatus.setIndentation(10)
        self.trwRealTimeStatus.setRootIsDecorated(True)
        self.trwRealTimeStatus.setUniformRowHeights(False)
        self.trwRealTimeStatus.setItemsExpandable(True)
        self.trwRealTimeStatus.setAllColumnsShowFocus(False)
        self.trwRealTimeStatus.setHeaderHidden(False)
        self.trwRealTimeStatus.setExpandsOnDoubleClick(False)
        self.trwRealTimeStatus.setObjectName("trwRealTimeStatus")
        self.trwRealTimeStatus.headerItem().setTextAlignment(0, QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.trwRealTimeStatus.header().setVisible(True)
        self.trwRealTimeStatus.header().setCascadingSectionResizes(False)
        self.trwRealTimeStatus.header().setDefaultSectionSize(120)
        self.trwRealTimeStatus.header().setMinimumSectionSize(50)
        self.trwRealTimeStatus.header().setSortIndicatorShown(False)
        self.trwRealTimeStatus.header().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.trwRealTimeStatus)
        self.stkwFunctionArea = QtWidgets.QStackedWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stkwFunctionArea.sizePolicy().hasHeightForWidth())
        self.stkwFunctionArea.setSizePolicy(sizePolicy)
        self.stkwFunctionArea.setMinimumSize(QtCore.QSize(0, 0))
        self.stkwFunctionArea.setBaseSize(QtCore.QSize(0, 0))
        self.stkwFunctionArea.setObjectName("stkwFunctionArea")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.stkwFunctionArea.addWidget(self.page_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lblMotionStatus = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMotionStatus.sizePolicy().hasHeightForWidth())
        self.lblMotionStatus.setSizePolicy(sizePolicy)
        self.lblMotionStatus.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblMotionStatus.setFont(font)
        self.lblMotionStatus.setText("")
        self.lblMotionStatus.setObjectName("lblMotionStatus")
        self.horizontalLayout.addWidget(self.lblMotionStatus)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.ledGreen = QtWidgets.QLabel(self.layoutWidget1)
        self.ledGreen.setMinimumSize(QtCore.QSize(40, 40))
        self.ledGreen.setText("")
        self.ledGreen.setObjectName("ledGreen")
        self.horizontalLayout.addWidget(self.ledGreen)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.ledYellow = QtWidgets.QLabel(self.layoutWidget1)
        self.ledYellow.setMinimumSize(QtCore.QSize(40, 40))
        self.ledYellow.setText("")
        self.ledYellow.setObjectName("ledYellow")
        self.horizontalLayout.addWidget(self.ledYellow)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.ledRed = QtWidgets.QLabel(self.layoutWidget1)
        self.ledRed.setMinimumSize(QtCore.QSize(40, 40))
        self.ledRed.setText("")
        self.ledRed.setObjectName("ledRed")
        self.horizontalLayout.addWidget(self.ledRed)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1800, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menuFile.setObjectName("menuFile")
        self.menuImport = QtWidgets.QMenu(self.menuFile)
        self.menuImport.setObjectName("menuImport")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setStatusTip("")
        self.menuTool.setObjectName("menuTool")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuDocument = QtWidgets.QMenu(self.menuHelp)
        self.menuDocument.setObjectName("menuDocument")
        self.menuUpgrade = QtWidgets.QMenu(self.menubar)
        self.menuUpgrade.setObjectName("menuUpgrade")
        MainWindow.setMenuBar(self.menubar)
        self.sbMainWin = QtWidgets.QStatusBar(MainWindow)
        self.sbMainWin.setObjectName("sbMainWin")
        MainWindow.setStatusBar(self.sbMainWin)
        self.toolBar_3 = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.toolBar_3.setFont(font)
        self.toolBar_3.setStatusTip("")
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.mnuSave = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icon/iconfinder_Save_85542.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuSave.setIcon(icon)
        self.mnuSave.setStatusTip("")
        self.mnuSave.setObjectName("mnuSave")
        self.mnuStart = QtWidgets.QAction(MainWindow)
        self.mnuStart.setCheckable(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Icon/iconfinder_Play01_928430.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuStart.setIcon(icon1)
        self.mnuStart.setStatusTip("")
        self.mnuStart.setObjectName("mnuStart")
        self.mnuStop = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Icon/iconfinder_multimedia-53_809515.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuStop.setIcon(icon2)
        self.mnuStop.setStatusTip("")
        self.mnuStop.setObjectName("mnuStop")
        self.mnuPause = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Icon/iconfinder_music_pause_stop_control_play_1868969.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuPause.setIcon(icon3)
        self.mnuPause.setStatusTip("")
        self.mnuPause.setObjectName("mnuPause")
        self.mnuCommConn = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../img/iconfinder_21-usb-installed-512x512_265510.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuCommConn.setIcon(icon4)
        self.mnuCommConn.setStatusTip("")
        self.mnuCommConn.setObjectName("mnuCommConn")
        self.actionPipe_On = QtWidgets.QAction(MainWindow)
        self.actionPipe_On.setObjectName("actionPipe_On")
        self.mnuCommClose = QtWidgets.QAction(MainWindow)
        self.mnuCommClose.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../img/iconfinder_22-usb-not-installed-512x512_265507.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuCommClose.setIcon(icon5)
        self.mnuCommClose.setObjectName("mnuCommClose")
        self.actionPipe_Off = QtWidgets.QAction(MainWindow)
        self.actionPipe_Off.setObjectName("actionPipe_Off")
        self.actionasdf = QtWidgets.QAction(MainWindow)
        self.actionasdf.setObjectName("actionasdf")
        self.mnuAbout = QtWidgets.QAction(MainWindow)
        self.mnuAbout.setObjectName("mnuAbout")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.mnuImportScriptFile = QtWidgets.QAction(MainWindow)
        self.mnuImportScriptFile.setObjectName("mnuImportScriptFile")
        self.mnuImportPointFile = QtWidgets.QAction(MainWindow)
        self.mnuImportPointFile.setObjectName("mnuImportPointFile")
        self.mnuImportMotionReportFile = QtWidgets.QAction(MainWindow)
        self.mnuImportMotionReportFile.setObjectName("mnuImportMotionReportFile")
        self.mnuServo_Report_File = QtWidgets.QAction(MainWindow)
        self.mnuServo_Report_File.setObjectName("mnuServo_Report_File")
        self.mnuServo_Parameter_File = QtWidgets.QAction(MainWindow)
        self.mnuServo_Parameter_File.setObjectName("mnuServo_Parameter_File")
        self.mnuExportScriptFile = QtWidgets.QAction(MainWindow)
        self.mnuExportScriptFile.setObjectName("mnuExportScriptFile")
        self.mnuExportPointFile = QtWidgets.QAction(MainWindow)
        self.mnuExportPointFile.setObjectName("mnuExportPointFile")
        self.mnuExportMotionReportFile = QtWidgets.QAction(MainWindow)
        self.mnuExportMotionReportFile.setObjectName("mnuExportMotionReportFile")
        self.mnuExportServoReportFile = QtWidgets.QAction(MainWindow)
        self.mnuExportServoReportFile.setObjectName("mnuExportServoReportFile")
        self.mnuExportServoParameterFile = QtWidgets.QAction(MainWindow)
        self.mnuExportServoParameterFile.setObjectName("mnuExportServoParameterFile")
        self.mnuDownloadFirmware = QtWidgets.QAction(MainWindow)
        self.mnuDownloadFirmware.setObjectName("mnuDownloadFirmware")
        self.mnuDownloadParameter = QtWidgets.QAction(MainWindow)
        self.mnuDownloadParameter.setObjectName("mnuDownloadParameter")
        self.mnuExit = QtWidgets.QAction(MainWindow)
        self.mnuExit.setObjectName("mnuExit")
        self.mnuAxRobotUserGuide = QtWidgets.QAction(MainWindow)
        self.mnuAxRobotUserGuide.setObjectName("mnuAxRobotUserGuide")
        self.menuImport.addAction(self.mnuImportScriptFile)
        self.menuImport.addAction(self.mnuImportPointFile)
        self.menuExport.addAction(self.mnuExportScriptFile)
        self.menuExport.addAction(self.mnuExportPointFile)
        self.menuExport.addAction(self.mnuExportMotionReportFile)
        self.menuExport.addAction(self.mnuExportServoReportFile)
        self.menuExport.addAction(self.mnuExportServoParameterFile)
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addAction(self.mnuExit)
        self.menuTool.addAction(self.mnuCommConn)
        self.menuTool.addAction(self.mnuCommClose)
        self.menuDocument.addAction(self.mnuAxRobotUserGuide)
        self.menuHelp.addAction(self.menuDocument.menuAction())
        self.menuHelp.addAction(self.mnuAbout)
        self.menuUpgrade.addAction(self.mnuDownloadFirmware)
        self.menuUpgrade.addAction(self.mnuDownloadParameter)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuUpgrade.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar_3.addAction(self.mnuCommConn)
        self.toolBar_3.addAction(self.mnuCommClose)
        self.toolBar_3.addSeparator()

        self.retranslateUi(MainWindow)
        self.stkwFunctionArea.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AxRobotUtility"))
        self.label.setText(_translate("MainWindow", "Function Selector: "))
        __sortingEnabled = self.lstwFunctionSelector.isSortingEnabled()
        self.lstwFunctionSelector.setSortingEnabled(False)
        item = self.lstwFunctionSelector.item(0)
        item.setText(_translate("MainWindow", "StartUp"))
        item = self.lstwFunctionSelector.item(1)
        item.setText(_translate("MainWindow", "Parameter Viewer"))
        item = self.lstwFunctionSelector.item(2)
        item.setText(_translate("MainWindow", "Jog Control"))
        item = self.lstwFunctionSelector.item(3)
        item.setText(_translate("MainWindow", "Point Editor"))
        item = self.lstwFunctionSelector.item(4)
        item.setText(_translate("MainWindow", "Script Editor"))
        item = self.lstwFunctionSelector.item(5)
        item.setText(_translate("MainWindow", "Motion Tuner"))
        item = self.lstwFunctionSelector.item(6)
        item.setText(_translate("MainWindow", "Upgrade"))
        self.lstwFunctionSelector.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Real Time Status:"))
        self.btnRealTimeStatusExpandAll.setText(_translate("MainWindow", "Expand All"))
        self.trwRealTimeStatus.setSortingEnabled(False)
        self.trwRealTimeStatus.headerItem().setText(0, _translate("MainWindow", "Item"))
        self.trwRealTimeStatus.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.trwRealTimeStatus.headerItem().setText(2, _translate("MainWindow", "Unit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_3.setText(_translate("MainWindow", "Motion Status:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuTool.setTitle(_translate("MainWindow", "Tool"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuDocument.setTitle(_translate("MainWindow", "Document"))
        self.menuUpgrade.setTitle(_translate("MainWindow", "Upgrade"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
        self.mnuSave.setText(_translate("MainWindow", "Save"))
        self.mnuSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.mnuStart.setText(_translate("MainWindow", "Start"))
        self.mnuStart.setShortcut(_translate("MainWindow", "F5"))
        self.mnuStop.setText(_translate("MainWindow", "Stop"))
        self.mnuPause.setText(_translate("MainWindow", "Pause"))
        self.mnuCommConn.setText(_translate("MainWindow", "Connect"))
        self.actionPipe_On.setText(_translate("MainWindow", "Pipe On"))
        self.mnuCommClose.setText(_translate("MainWindow", "Disconnect"))
        self.actionPipe_Off.setText(_translate("MainWindow", "Pipe Off"))
        self.actionasdf.setText(_translate("MainWindow", "asdf"))
        self.mnuAbout.setText(_translate("MainWindow", "About"))
        self.action.setText(_translate("MainWindow", "Restart"))
        self.mnuImportScriptFile.setText(_translate("MainWindow", "Script File"))
        self.mnuImportPointFile.setText(_translate("MainWindow", "Point File"))
        self.mnuImportMotionReportFile.setText(_translate("MainWindow", "Motion Report File"))
        self.mnuServo_Report_File.setText(_translate("MainWindow", "Servo Report File"))
        self.mnuServo_Parameter_File.setText(_translate("MainWindow", "Servo Parameter File"))
        self.mnuExportScriptFile.setText(_translate("MainWindow", "Script File"))
        self.mnuExportPointFile.setText(_translate("MainWindow", "Point File"))
        self.mnuExportMotionReportFile.setText(_translate("MainWindow", "Motion Report File"))
        self.mnuExportServoReportFile.setText(_translate("MainWindow", "Servo Report File"))
        self.mnuExportServoParameterFile.setText(_translate("MainWindow", "Servo Parameter File"))
        self.mnuDownloadFirmware.setText(_translate("MainWindow", "Download Firmware"))
        self.mnuDownloadParameter.setText(_translate("MainWindow", "Download Parameter"))
        self.mnuExit.setText(_translate("MainWindow", "Exit"))
        self.mnuAxRobotUserGuide.setText(_translate("MainWindow", "AxRobot User Guide"))
