# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/frmAbout.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormAbout(object):
    def setupUi(self, FormAbout):
        FormAbout.setObjectName("FormAbout")
        FormAbout.resize(682, 393)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FormAbout.sizePolicy().hasHeightForWidth())
        FormAbout.setSizePolicy(sizePolicy)
        FormAbout.setMinimumSize(QtCore.QSize(682, 393))
        FormAbout.setMaximumSize(QtCore.QSize(682, 393))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        FormAbout.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FormAbout)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbTitle = QtWidgets.QLabel(FormAbout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbTitle.sizePolicy().hasHeightForWidth())
        self.lbTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lbTitle.setFont(font)
        self.lbTitle.setScaledContents(False)
        self.lbTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTitle.setObjectName("lbTitle")
        self.verticalLayout_2.addWidget(self.lbTitle)
        self.lbInfoIcon = QtWidgets.QLabel(FormAbout)
        self.lbInfoIcon.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbInfoIcon.setFont(font)
        self.lbInfoIcon.setObjectName("lbInfoIcon")
        self.verticalLayout_2.addWidget(self.lbInfoIcon)
        self.label_4 = QtWidgets.QLabel(FormAbout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.lbInfo = QtWidgets.QLabel(FormAbout)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbInfo.setFont(font)
        self.lbInfo.setObjectName("lbInfo")
        self.verticalLayout_2.addWidget(self.lbInfo)
        self.label_3 = QtWidgets.QLabel(FormAbout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lbAsixLink = QtWidgets.QLabel(FormAbout)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbAsixLink.setFont(font)
        self.lbAsixLink.setObjectName("lbAsixLink")
        self.verticalLayout_2.addWidget(self.lbAsixLink)
        self.label_6 = QtWidgets.QLabel(FormAbout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnCloseAbout = QtWidgets.QPushButton(FormAbout)
        self.btnCloseAbout.setMinimumSize(QtCore.QSize(0, 50))
        self.btnCloseAbout.setObjectName("btnCloseAbout")
        self.horizontalLayout.addWidget(self.btnCloseAbout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(FormAbout)
        QtCore.QMetaObject.connectSlotsByName(FormAbout)

    def retranslateUi(self, FormAbout):
        _translate = QtCore.QCoreApplication.translate
        FormAbout.setWindowTitle(_translate("FormAbout", "About"))
        self.lbTitle.setText(_translate("FormAbout", "Title"))
        self.lbInfoIcon.setText(_translate("FormAbout", "InfoIcon"))
        self.lbInfo.setText(_translate("FormAbout", "Info"))
        self.lbAsixLink.setText(_translate("FormAbout", "AxisLink"))
        self.btnCloseAbout.setText(_translate("FormAbout", "OK"))
