# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/frmJogControl.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(824, 742)
        self.gridLayout_5 = QtWidgets.QGridLayout(Form)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stkwJogControl = QtWidgets.QStackedWidget(self.groupBox)
        self.stkwJogControl.setObjectName("stkwJogControl")
        self.JointPage = QtWidgets.QWidget()
        self.JointPage.setObjectName("JointPage")
        self.gridLayout = QtWidgets.QGridLayout(self.JointPage)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(20)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.JointPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.JointPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.JointPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.JointPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.JointPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.JointPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.JointPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.gridLayout.addLayout(self.verticalLayout_9, 0, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(20)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnJ1Sub = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ1Sub.setFont(font)
        self.btnJ1Sub.setObjectName("btnJ1Sub")
        self.verticalLayout_8.addWidget(self.btnJ1Sub)
        self.btnJ2Sub = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ2Sub.setFont(font)
        self.btnJ2Sub.setObjectName("btnJ2Sub")
        self.verticalLayout_8.addWidget(self.btnJ2Sub)
        self.btnJ3Sub = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ3Sub.setFont(font)
        self.btnJ3Sub.setObjectName("btnJ3Sub")
        self.verticalLayout_8.addWidget(self.btnJ3Sub)
        self.btnJ4Sub = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ4Sub.setFont(font)
        self.btnJ4Sub.setObjectName("btnJ4Sub")
        self.verticalLayout_8.addWidget(self.btnJ4Sub)
        self.btnJ5Sub = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ5Sub.setFont(font)
        self.btnJ5Sub.setObjectName("btnJ5Sub")
        self.verticalLayout_8.addWidget(self.btnJ5Sub)
        self.btnJ6Sub = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ6Sub.setFont(font)
        self.btnJ6Sub.setObjectName("btnJ6Sub")
        self.verticalLayout_8.addWidget(self.btnJ6Sub)
        self.btnJ7Sub = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ7Sub.setFont(font)
        self.btnJ7Sub.setObjectName("btnJ7Sub")
        self.verticalLayout_8.addWidget(self.btnJ7Sub)
        self.gridLayout.addLayout(self.verticalLayout_8, 0, 2, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(20)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btnJ1Add = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ1Add.setFont(font)
        self.btnJ1Add.setObjectName("btnJ1Add")
        self.verticalLayout_7.addWidget(self.btnJ1Add)
        self.btnJ2Add = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ2Add.setFont(font)
        self.btnJ2Add.setObjectName("btnJ2Add")
        self.verticalLayout_7.addWidget(self.btnJ2Add)
        self.btnJ3Add = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ3Add.setFont(font)
        self.btnJ3Add.setObjectName("btnJ3Add")
        self.verticalLayout_7.addWidget(self.btnJ3Add)
        self.btnJ4Add = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ4Add.setFont(font)
        self.btnJ4Add.setObjectName("btnJ4Add")
        self.verticalLayout_7.addWidget(self.btnJ4Add)
        self.btnJ5Add = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ5Add.setFont(font)
        self.btnJ5Add.setObjectName("btnJ5Add")
        self.verticalLayout_7.addWidget(self.btnJ5Add)
        self.btnJ6Add = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ6Add.setFont(font)
        self.btnJ6Add.setObjectName("btnJ6Add")
        self.verticalLayout_7.addWidget(self.btnJ6Add)
        self.btnJ7Add = QtWidgets.QPushButton(self.JointPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnJ7Add.setFont(font)
        self.btnJ7Add.setObjectName("btnJ7Add")
        self.verticalLayout_7.addWidget(self.btnJ7Add)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.stkwJogControl.addWidget(self.JointPage)
        self.TcpPage = QtWidgets.QWidget()
        self.TcpPage.setObjectName("TcpPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.TcpPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnTcpXAdd = QtWidgets.QPushButton(self.TcpPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnTcpXAdd.setFont(font)
        self.btnTcpXAdd.setObjectName("btnTcpXAdd")
        self.verticalLayout_4.addWidget(self.btnTcpXAdd)
        self.btnTcpYAdd = QtWidgets.QPushButton(self.TcpPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnTcpYAdd.setFont(font)
        self.btnTcpYAdd.setObjectName("btnTcpYAdd")
        self.verticalLayout_4.addWidget(self.btnTcpYAdd)
        self.btnTcpZAdd = QtWidgets.QPushButton(self.TcpPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnTcpZAdd.setFont(font)
        self.btnTcpZAdd.setObjectName("btnTcpZAdd")
        self.verticalLayout_4.addWidget(self.btnTcpZAdd)
        self.btnTcpRxAdd = QtWidgets.QPushButton(self.TcpPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnTcpRxAdd.setFont(font)
        self.btnTcpRxAdd.setObjectName("btnTcpRxAdd")
        self.verticalLayout_4.addWidget(self.btnTcpRxAdd)
        self.btnTcpRyAdd = QtWidgets.QPushButton(self.TcpPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnTcpRyAdd.setFont(font)
        self.btnTcpRyAdd.setObjectName("btnTcpRyAdd")
        self.verticalLayout_4.addWidget(self.btnTcpRyAdd)
        self.btnTcpRzAdd = QtWidgets.QPushButton(self.TcpPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnTcpRzAdd.setFont(font)
        self.btnTcpRzAdd.setObjectName("btnTcpRzAdd")
        self.verticalLayout_4.addWidget(self.btnTcpRzAdd)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnTcpXSub = QtWidgets.QPushButton(self.TcpPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnTcpXSub.setFont(font)
        self.btnTcpXSub.setObjectName("btnTcpXSub")
        self.verticalLayout_5.addWidget(self.btnTcpXSub)
        self.btnTcpYSub = QtWidgets.QPushButton(self.TcpPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnTcpYSub.setFont(font)
        self.btnTcpYSub.setObjectName("btnTcpYSub")
        self.verticalLayout_5.addWidget(self.btnTcpYSub)
        self.btnTcpZSub = QtWidgets.QPushButton(self.TcpPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnTcpZSub.setFont(font)
        self.btnTcpZSub.setObjectName("btnTcpZSub")
        self.verticalLayout_5.addWidget(self.btnTcpZSub)
        self.btnTcpRxSub = QtWidgets.QPushButton(self.TcpPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnTcpRxSub.setFont(font)
        self.btnTcpRxSub.setObjectName("btnTcpRxSub")
        self.verticalLayout_5.addWidget(self.btnTcpRxSub)
        self.btnTcpRySub = QtWidgets.QPushButton(self.TcpPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnTcpRySub.setFont(font)
        self.btnTcpRySub.setObjectName("btnTcpRySub")
        self.verticalLayout_5.addWidget(self.btnTcpRySub)
        self.btnTcpRzSub = QtWidgets.QPushButton(self.TcpPage)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnTcpRzSub.setFont(font)
        self.btnTcpRzSub.setObjectName("btnTcpRzSub")
        self.verticalLayout_5.addWidget(self.btnTcpRzSub)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 2, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(20)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_16 = QtWidgets.QLabel(self.TcpPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_6.addWidget(self.label_16)
        self.label_11 = QtWidgets.QLabel(self.TcpPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.TcpPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.label_14 = QtWidgets.QLabel(self.TcpPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.label_17 = QtWidgets.QLabel(self.TcpPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_6.addWidget(self.label_17)
        self.label_13 = QtWidgets.QLabel(self.TcpPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.stkwJogControl.addWidget(self.TcpPage)
        self.gridLayout_3.addWidget(self.stkwJogControl, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, 80, -1, 0)
        self.gridLayout_4.setHorizontalSpacing(10)
        self.gridLayout_4.setVerticalSpacing(20)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_15 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cboMode = QtWidgets.QComboBox(Form)
        self.cboMode.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cboMode.setFont(font)
        self.cboMode.setObjectName("cboMode")
        self.verticalLayout_2.addWidget(self.cboMode)
        self.cboSpeed = QtWidgets.QComboBox(Form)
        self.cboSpeed.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cboSpeed.setFont(font)
        self.cboSpeed.setObjectName("cboSpeed")
        self.verticalLayout_2.addWidget(self.cboSpeed)
        self.cboDistance = QtWidgets.QComboBox(Form)
        self.cboDistance.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cboDistance.setFont(font)
        self.cboDistance.setObjectName("cboDistance")
        self.verticalLayout_2.addWidget(self.cboDistance)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.label_10 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_18 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 2, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 1, 1)

        self.retranslateUi(Form)
        self.stkwJogControl.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Jog Control"))
        self.label.setText(_translate("Form", "Joint 1"))
        self.label_2.setText(_translate("Form", "Joint 2"))
        self.label_4.setText(_translate("Form", "Joint 3"))
        self.label_3.setText(_translate("Form", "Joint 4"))
        self.label_6.setText(_translate("Form", "Joint 5"))
        self.label_5.setText(_translate("Form", "Joint 6"))
        self.label_7.setText(_translate("Form", "Joint 7"))
        self.btnJ1Sub.setText(_translate("Form", "-"))
        self.btnJ2Sub.setText(_translate("Form", "-"))
        self.btnJ3Sub.setText(_translate("Form", "-"))
        self.btnJ4Sub.setText(_translate("Form", "-"))
        self.btnJ5Sub.setText(_translate("Form", "-"))
        self.btnJ6Sub.setText(_translate("Form", "-"))
        self.btnJ7Sub.setText(_translate("Form", "-"))
        self.btnJ1Add.setText(_translate("Form", "+"))
        self.btnJ2Add.setText(_translate("Form", "+"))
        self.btnJ3Add.setText(_translate("Form", "+"))
        self.btnJ4Add.setText(_translate("Form", "+"))
        self.btnJ5Add.setText(_translate("Form", "+"))
        self.btnJ6Add.setText(_translate("Form", "+"))
        self.btnJ7Add.setText(_translate("Form", "+"))
        self.btnTcpXAdd.setText(_translate("Form", "+"))
        self.btnTcpYAdd.setText(_translate("Form", "+"))
        self.btnTcpZAdd.setText(_translate("Form", "+"))
        self.btnTcpRxAdd.setText(_translate("Form", "+"))
        self.btnTcpRyAdd.setText(_translate("Form", "+"))
        self.btnTcpRzAdd.setText(_translate("Form", "+"))
        self.btnTcpXSub.setText(_translate("Form", "-"))
        self.btnTcpYSub.setText(_translate("Form", "-"))
        self.btnTcpZSub.setText(_translate("Form", "-"))
        self.btnTcpRxSub.setText(_translate("Form", "-"))
        self.btnTcpRySub.setText(_translate("Form", "-"))
        self.btnTcpRzSub.setText(_translate("Form", "-"))
        self.label_16.setText(_translate("Form", "X"))
        self.label_11.setText(_translate("Form", "Y"))
        self.label_12.setText(_translate("Form", "Z"))
        self.label_14.setText(_translate("Form", "RX"))
        self.label_17.setText(_translate("Form", "RY"))
        self.label_13.setText(_translate("Form", "RZ"))
        self.label_8.setText(_translate("Form", "Mode: "))
        self.label_9.setText(_translate("Form", "Speed: "))
        self.label_15.setText(_translate("Form", "Distance: "))
        self.label_10.setText(_translate("Form", "mm/s(deg/s)"))
        self.label_18.setText(_translate("Form", "mm(deg)"))
