# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/frmMotionTuner.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(962, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbwMotionTuner = QtWidgets.QTabWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tbwMotionTuner.setFont(font)
        self.tbwMotionTuner.setObjectName("tbwMotionTuner")
        self.GravityFactor = QtWidgets.QWidget()
        self.GravityFactor.setObjectName("GravityFactor")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.GravityFactor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxGravityCalculate = QtWidgets.QGroupBox(self.GravityFactor)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBoxGravityCalculate.setFont(font)
        self.groupBoxGravityCalculate.setObjectName("groupBoxGravityCalculate")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxGravityCalculate)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(430, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 3, 1, 1)
        self.label7 = QtWidgets.QLabel(self.groupBoxGravityCalculate)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label7.setFont(font)
        self.label7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label7.setObjectName("label7")
        self.gridLayout_2.addWidget(self.label7, 2, 1, 1, 1)
        self.btnGravityDistribution = QtWidgets.QPushButton(self.groupBoxGravityCalculate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGravityDistribution.sizePolicy().hasHeightForWidth())
        self.btnGravityDistribution.setSizePolicy(sizePolicy)
        self.btnGravityDistribution.setMinimumSize(QtCore.QSize(150, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnGravityDistribution.setFont(font)
        self.btnGravityDistribution.setObjectName("btnGravityDistribution")
        self.gridLayout_2.addWidget(self.btnGravityDistribution, 4, 4, 2, 1)
        self.leToolWeight = QtWidgets.QLineEdit(self.groupBoxGravityCalculate)
        self.leToolWeight.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leToolWeight.sizePolicy().hasHeightForWidth())
        self.leToolWeight.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leToolWeight.setFont(font)
        self.leToolWeight.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leToolWeight.setAlignment(QtCore.Qt.AlignCenter)
        self.leToolWeight.setObjectName("leToolWeight")
        self.gridLayout_2.addWidget(self.leToolWeight, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBoxGravityCalculate)
        self.groupBoxGravityAdjustment = QtWidgets.QGroupBox(self.GravityFactor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxGravityAdjustment.sizePolicy().hasHeightForWidth())
        self.groupBoxGravityAdjustment.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBoxGravityAdjustment.setFont(font)
        self.groupBoxGravityAdjustment.setObjectName("groupBoxGravityAdjustment")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxGravityAdjustment)
        self.gridLayout.setObjectName("gridLayout")
        self.btnGravityFactorMeasure = QtWidgets.QPushButton(self.groupBoxGravityAdjustment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGravityFactorMeasure.sizePolicy().hasHeightForWidth())
        self.btnGravityFactorMeasure.setSizePolicy(sizePolicy)
        self.btnGravityFactorMeasure.setMinimumSize(QtCore.QSize(150, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnGravityFactorMeasure.setFont(font)
        self.btnGravityFactorMeasure.setObjectName("btnGravityFactorMeasure")
        self.gridLayout.addWidget(self.btnGravityFactorMeasure, 5, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.label8 = QtWidgets.QLabel(self.groupBoxGravityAdjustment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label8.sizePolicy().hasHeightForWidth())
        self.label8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label8.setFont(font)
        self.label8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label8.setObjectName("label8")
        self.gridLayout.addWidget(self.label8, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 5, 1, 1)
        self.cboGravityAngle = QtWidgets.QComboBox(self.groupBoxGravityAdjustment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboGravityAngle.sizePolicy().hasHeightForWidth())
        self.cboGravityAngle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cboGravityAngle.setFont(font)
        self.cboGravityAngle.setObjectName("cboGravityAngle")
        self.gridLayout.addWidget(self.cboGravityAngle, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 1)
        self.label9 = QtWidgets.QLabel(self.groupBoxGravityAdjustment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label9.sizePolicy().hasHeightForWidth())
        self.label9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label9.setFont(font)
        self.label9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label9.setObjectName("label9")
        self.gridLayout.addWidget(self.label9, 1, 0, 1, 1)
        self.cboGravityAxis = QtWidgets.QComboBox(self.groupBoxGravityAdjustment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboGravityAxis.sizePolicy().hasHeightForWidth())
        self.cboGravityAxis.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cboGravityAxis.setFont(font)
        self.cboGravityAxis.setObjectName("cboGravityAxis")
        self.gridLayout.addWidget(self.cboGravityAxis, 0, 1, 1, 1)
        self.label10 = QtWidgets.QLabel(self.groupBoxGravityAdjustment)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label10.setFont(font)
        self.label10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label10.setObjectName("label10")
        self.gridLayout.addWidget(self.label10, 2, 0, 1, 1)
        self.leGravitySamplingTime = QtWidgets.QLineEdit(self.groupBoxGravityAdjustment)
        self.leGravitySamplingTime.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leGravitySamplingTime.sizePolicy().hasHeightForWidth())
        self.leGravitySamplingTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leGravitySamplingTime.setFont(font)
        self.leGravitySamplingTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leGravitySamplingTime.setAlignment(QtCore.Qt.AlignCenter)
        self.leGravitySamplingTime.setObjectName("leGravitySamplingTime")
        self.gridLayout.addWidget(self.leGravitySamplingTime, 2, 1, 1, 1)
        self.label11_3 = QtWidgets.QLabel(self.groupBoxGravityAdjustment)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label11_3.setFont(font)
        self.label11_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label11_3.setObjectName("label11_3")
        self.gridLayout.addWidget(self.label11_3, 2, 3, 1, 1)
        self.leGravityInitialFactor = QtWidgets.QLineEdit(self.groupBoxGravityAdjustment)
        self.leGravityInitialFactor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leGravityInitialFactor.sizePolicy().hasHeightForWidth())
        self.leGravityInitialFactor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leGravityInitialFactor.setFont(font)
        self.leGravityInitialFactor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leGravityInitialFactor.setAlignment(QtCore.Qt.AlignCenter)
        self.leGravityInitialFactor.setObjectName("leGravityInitialFactor")
        self.gridLayout.addWidget(self.leGravityInitialFactor, 2, 4, 1, 1)
        self.label11_2 = QtWidgets.QLabel(self.groupBoxGravityAdjustment)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label11_2.setFont(font)
        self.label11_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label11_2.setObjectName("label11_2")
        self.gridLayout.addWidget(self.label11_2, 0, 3, 1, 1)
        self.leGravitySpeedLimit = QtWidgets.QLineEdit(self.groupBoxGravityAdjustment)
        self.leGravitySpeedLimit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leGravitySpeedLimit.sizePolicy().hasHeightForWidth())
        self.leGravitySpeedLimit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leGravitySpeedLimit.setFont(font)
        self.leGravitySpeedLimit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leGravitySpeedLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.leGravitySpeedLimit.setObjectName("leGravitySpeedLimit")
        self.gridLayout.addWidget(self.leGravitySpeedLimit, 0, 4, 1, 1)
        self.label11 = QtWidgets.QLabel(self.groupBoxGravityAdjustment)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label11.setFont(font)
        self.label11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label11.setObjectName("label11")
        self.gridLayout.addWidget(self.label11, 1, 3, 1, 1)
        self.leGravitySpeed = QtWidgets.QLineEdit(self.groupBoxGravityAdjustment)
        self.leGravitySpeed.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leGravitySpeed.sizePolicy().hasHeightForWidth())
        self.leGravitySpeed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leGravitySpeed.setFont(font)
        self.leGravitySpeed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leGravitySpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.leGravitySpeed.setObjectName("leGravitySpeed")
        self.gridLayout.addWidget(self.leGravitySpeed, 1, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBoxGravityAdjustment)
        self.groupBoxGravityAdjustment_2 = QtWidgets.QGroupBox(self.GravityFactor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxGravityAdjustment_2.sizePolicy().hasHeightForWidth())
        self.groupBoxGravityAdjustment_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBoxGravityAdjustment_2.setFont(font)
        self.groupBoxGravityAdjustment_2.setObjectName("groupBoxGravityAdjustment_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxGravityAdjustment_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 3, 0, 1, 1)
        self.label14 = QtWidgets.QLabel(self.groupBoxGravityAdjustment_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label14.setFont(font)
        self.label14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label14.setObjectName("label14")
        self.gridLayout_3.addWidget(self.label14, 2, 0, 1, 1)
        self.label13 = QtWidgets.QLabel(self.groupBoxGravityAdjustment_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label13.setFont(font)
        self.label13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label13.setObjectName("label13")
        self.gridLayout_3.addWidget(self.label13, 1, 0, 1, 1)
        self.leSampledPoints = QtWidgets.QLineEdit(self.groupBoxGravityAdjustment_2)
        self.leSampledPoints.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leSampledPoints.sizePolicy().hasHeightForWidth())
        self.leSampledPoints.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leSampledPoints.setFont(font)
        self.leSampledPoints.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leSampledPoints.setAlignment(QtCore.Qt.AlignCenter)
        self.leSampledPoints.setObjectName("leSampledPoints")
        self.gridLayout_3.addWidget(self.leSampledPoints, 0, 4, 1, 1)
        self.leAverageGravity = QtWidgets.QLineEdit(self.groupBoxGravityAdjustment_2)
        self.leAverageGravity.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAverageGravity.sizePolicy().hasHeightForWidth())
        self.leAverageGravity.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leAverageGravity.setFont(font)
        self.leAverageGravity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leAverageGravity.setAlignment(QtCore.Qt.AlignCenter)
        self.leAverageGravity.setObjectName("leAverageGravity")
        self.gridLayout_3.addWidget(self.leAverageGravity, 1, 1, 1, 1)
        self.leAverageTorque = QtWidgets.QLineEdit(self.groupBoxGravityAdjustment_2)
        self.leAverageTorque.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAverageTorque.sizePolicy().hasHeightForWidth())
        self.leAverageTorque.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leAverageTorque.setFont(font)
        self.leAverageTorque.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leAverageTorque.setAlignment(QtCore.Qt.AlignCenter)
        self.leAverageTorque.setObjectName("leAverageTorque")
        self.gridLayout_3.addWidget(self.leAverageTorque, 2, 1, 1, 1)
        self.leGravityFactor = QtWidgets.QLineEdit(self.groupBoxGravityAdjustment_2)
        self.leGravityFactor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leGravityFactor.sizePolicy().hasHeightForWidth())
        self.leGravityFactor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leGravityFactor.setFont(font)
        self.leGravityFactor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leGravityFactor.setAlignment(QtCore.Qt.AlignCenter)
        self.leGravityFactor.setObjectName("leGravityFactor")
        self.gridLayout_3.addWidget(self.leGravityFactor, 0, 1, 1, 1)
        self.label12 = QtWidgets.QLabel(self.groupBoxGravityAdjustment_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label12.setFont(font)
        self.label12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label12.setObjectName("label12")
        self.gridLayout_3.addWidget(self.label12, 0, 0, 1, 1)
        self.label15 = QtWidgets.QLabel(self.groupBoxGravityAdjustment_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label15.setFont(font)
        self.label15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label15.setObjectName("label15")
        self.gridLayout_3.addWidget(self.label15, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBoxGravityAdjustment_2)
        self.groupBoxGravityAdjustment.raise_()
        self.groupBoxGravityCalculate.raise_()
        self.groupBoxGravityAdjustment_2.raise_()
        self.tbwMotionTuner.addTab(self.GravityFactor, "")
        self.FrictionFactor = QtWidgets.QWidget()
        self.FrictionFactor.setObjectName("FrictionFactor")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.FrictionFactor)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBoxFriction = QtWidgets.QGroupBox(self.FrictionFactor)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBoxFriction.setFont(font)
        self.groupBoxFriction.setObjectName("groupBoxFriction")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxFriction)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBoxFriction)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 1, 1, 1)
        self.leFrictionMaxTestSpeed = QtWidgets.QLineEdit(self.groupBoxFriction)
        self.leFrictionMaxTestSpeed.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leFrictionMaxTestSpeed.sizePolicy().hasHeightForWidth())
        self.leFrictionMaxTestSpeed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leFrictionMaxTestSpeed.setFont(font)
        self.leFrictionMaxTestSpeed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leFrictionMaxTestSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.leFrictionMaxTestSpeed.setObjectName("leFrictionMaxTestSpeed")
        self.gridLayout_4.addWidget(self.leFrictionMaxTestSpeed, 2, 5, 1, 1)
        self.leFrictionMinTestSpeed = QtWidgets.QLineEdit(self.groupBoxFriction)
        self.leFrictionMinTestSpeed.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leFrictionMinTestSpeed.sizePolicy().hasHeightForWidth())
        self.leFrictionMinTestSpeed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leFrictionMinTestSpeed.setFont(font)
        self.leFrictionMinTestSpeed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leFrictionMinTestSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.leFrictionMinTestSpeed.setObjectName("leFrictionMinTestSpeed")
        self.gridLayout_4.addWidget(self.leFrictionMinTestSpeed, 1, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBoxFriction)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 4, 1, 1)
        self.leFrictionSpeedTestSections = QtWidgets.QLineEdit(self.groupBoxFriction)
        self.leFrictionSpeedTestSections.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leFrictionSpeedTestSections.sizePolicy().hasHeightForWidth())
        self.leFrictionSpeedTestSections.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leFrictionSpeedTestSections.setFont(font)
        self.leFrictionSpeedTestSections.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leFrictionSpeedTestSections.setAlignment(QtCore.Qt.AlignCenter)
        self.leFrictionSpeedTestSections.setObjectName("leFrictionSpeedTestSections")
        self.gridLayout_4.addWidget(self.leFrictionSpeedTestSections, 3, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBoxFriction)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 4, 1, 1)
        self.cboFrictionAngle = QtWidgets.QComboBox(self.groupBoxFriction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFrictionAngle.sizePolicy().hasHeightForWidth())
        self.cboFrictionAngle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cboFrictionAngle.setFont(font)
        self.cboFrictionAngle.setObjectName("cboFrictionAngle")
        self.gridLayout_4.addWidget(self.cboFrictionAngle, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBoxFriction)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBoxFriction)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBoxFriction)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 3, 4, 1, 1)
        self.leFrictionSpeedLimit = QtWidgets.QLineEdit(self.groupBoxFriction)
        self.leFrictionSpeedLimit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leFrictionSpeedLimit.sizePolicy().hasHeightForWidth())
        self.leFrictionSpeedLimit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leFrictionSpeedLimit.setFont(font)
        self.leFrictionSpeedLimit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leFrictionSpeedLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.leFrictionSpeedLimit.setObjectName("leFrictionSpeedLimit")
        self.gridLayout_4.addWidget(self.leFrictionSpeedLimit, 0, 5, 1, 1)
        self.cboFrictionAxis = QtWidgets.QComboBox(self.groupBoxFriction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFrictionAxis.sizePolicy().hasHeightForWidth())
        self.cboFrictionAxis.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cboFrictionAxis.setFont(font)
        self.cboFrictionAxis.setObjectName("cboFrictionAxis")
        self.gridLayout_4.addWidget(self.cboFrictionAxis, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBoxFriction)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 1, 1, 1)
        self.leFrictionSamplingTime = QtWidgets.QLineEdit(self.groupBoxFriction)
        self.leFrictionSamplingTime.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leFrictionSamplingTime.sizePolicy().hasHeightForWidth())
        self.leFrictionSamplingTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leFrictionSamplingTime.setFont(font)
        self.leFrictionSamplingTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leFrictionSamplingTime.setAlignment(QtCore.Qt.AlignCenter)
        self.leFrictionSamplingTime.setObjectName("leFrictionSamplingTime")
        self.gridLayout_4.addWidget(self.leFrictionSamplingTime, 2, 2, 1, 1)
        self.btnFrictionFactorMeasure = QtWidgets.QPushButton(self.groupBoxFriction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFrictionFactorMeasure.sizePolicy().hasHeightForWidth())
        self.btnFrictionFactorMeasure.setSizePolicy(sizePolicy)
        self.btnFrictionFactorMeasure.setMinimumSize(QtCore.QSize(150, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnFrictionFactorMeasure.setFont(font)
        self.btnFrictionFactorMeasure.setObjectName("btnFrictionFactorMeasure")
        self.gridLayout_4.addWidget(self.btnFrictionFactorMeasure, 5, 5, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBoxFriction)
        self.groupBox = QtWidgets.QGroupBox(self.FrictionFactor)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 4, 2, 1, 1)
        self.leDynamicFriction = QtWidgets.QLineEdit(self.groupBox)
        self.leDynamicFriction.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leDynamicFriction.sizePolicy().hasHeightForWidth())
        self.leDynamicFriction.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leDynamicFriction.setFont(font)
        self.leDynamicFriction.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leDynamicFriction.setAlignment(QtCore.Qt.AlignCenter)
        self.leDynamicFriction.setObjectName("leDynamicFriction")
        self.gridLayout_5.addWidget(self.leDynamicFriction, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 3, 0, 1, 1)
        self.leDraggedStaticFriction = QtWidgets.QLineEdit(self.groupBox)
        self.leDraggedStaticFriction.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leDraggedStaticFriction.sizePolicy().hasHeightForWidth())
        self.leDraggedStaticFriction.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leDraggedStaticFriction.setFont(font)
        self.leDraggedStaticFriction.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leDraggedStaticFriction.setAlignment(QtCore.Qt.AlignCenter)
        self.leDraggedStaticFriction.setObjectName("leDraggedStaticFriction")
        self.gridLayout_5.addWidget(self.leDraggedStaticFriction, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 4, 0, 1, 1)
        self.leDraggedDynamicFriction = QtWidgets.QLineEdit(self.groupBox)
        self.leDraggedDynamicFriction.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leDraggedDynamicFriction.sizePolicy().hasHeightForWidth())
        self.leDraggedDynamicFriction.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leDraggedDynamicFriction.setFont(font)
        self.leDraggedDynamicFriction.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leDraggedDynamicFriction.setAlignment(QtCore.Qt.AlignCenter)
        self.leDraggedDynamicFriction.setObjectName("leDraggedDynamicFriction")
        self.gridLayout_5.addWidget(self.leDraggedDynamicFriction, 4, 1, 1, 1)
        self.leStaticFriction = QtWidgets.QLineEdit(self.groupBox)
        self.leStaticFriction.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leStaticFriction.sizePolicy().hasHeightForWidth())
        self.leStaticFriction.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leStaticFriction.setFont(font)
        self.leStaticFriction.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leStaticFriction.setAlignment(QtCore.Qt.AlignCenter)
        self.leStaticFriction.setObjectName("leStaticFriction")
        self.gridLayout_5.addWidget(self.leStaticFriction, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem10, 5, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.tbwMotionTuner.addTab(self.FrictionFactor, "")
        self.extForceCompensation = QtWidgets.QWidget()
        self.extForceCompensation.setObjectName("extForceCompensation")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.extForceCompensation)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBoxExternal = QtWidgets.QGroupBox(self.extForceCompensation)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBoxExternal.setFont(font)
        self.groupBoxExternal.setObjectName("groupBoxExternal")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBoxExternal)
        self.verticalLayout_5.setSpacing(7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label17 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label17.setFont(font)
        self.label17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label17.setObjectName("label17")
        self.gridLayout_6.addWidget(self.label17, 1, 0, 1, 1)
        self.leExtSamplingTime = QtWidgets.QLineEdit(self.groupBoxExternal)
        self.leExtSamplingTime.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExtSamplingTime.sizePolicy().hasHeightForWidth())
        self.leExtSamplingTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leExtSamplingTime.setFont(font)
        self.leExtSamplingTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leExtSamplingTime.setAlignment(QtCore.Qt.AlignCenter)
        self.leExtSamplingTime.setObjectName("leExtSamplingTime")
        self.gridLayout_6.addWidget(self.leExtSamplingTime, 2, 1, 1, 1)
        self.cboExtForceAxis = QtWidgets.QComboBox(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cboExtForceAxis.setFont(font)
        self.cboExtForceAxis.setObjectName("cboExtForceAxis")
        self.gridLayout_6.addWidget(self.cboExtForceAxis, 0, 1, 1, 1)
        self.label18_2 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label18_2.setFont(font)
        self.label18_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label18_2.setObjectName("label18_2")
        self.gridLayout_6.addWidget(self.label18_2, 2, 0, 1, 1)
        self.cboExtForceAngle = QtWidgets.QComboBox(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cboExtForceAngle.setFont(font)
        self.cboExtForceAngle.setObjectName("cboExtForceAngle")
        self.gridLayout_6.addWidget(self.cboExtForceAngle, 1, 1, 1, 1)
        self.label16 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label16.setFont(font)
        self.label16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label16.setObjectName("label16")
        self.gridLayout_6.addWidget(self.label16, 0, 0, 1, 1)
        self.leExtSpeed = QtWidgets.QLineEdit(self.groupBoxExternal)
        self.leExtSpeed.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExtSpeed.sizePolicy().hasHeightForWidth())
        self.leExtSpeed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leExtSpeed.setFont(font)
        self.leExtSpeed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leExtSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.leExtSpeed.setObjectName("leExtSpeed")
        self.gridLayout_6.addWidget(self.leExtSpeed, 3, 1, 1, 1)
        self.label18 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label18.setFont(font)
        self.label18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label18.setObjectName("label18")
        self.gridLayout_6.addWidget(self.label18, 3, 0, 1, 1)
        self.leExtDecelerationLimit = QtWidgets.QLineEdit(self.groupBoxExternal)
        self.leExtDecelerationLimit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExtDecelerationLimit.sizePolicy().hasHeightForWidth())
        self.leExtDecelerationLimit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leExtDecelerationLimit.setFont(font)
        self.leExtDecelerationLimit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leExtDecelerationLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.leExtDecelerationLimit.setObjectName("leExtDecelerationLimit")
        self.gridLayout_6.addWidget(self.leExtDecelerationLimit, 0, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem11, 4, 2, 1, 1)
        self.label19 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label19.setFont(font)
        self.label19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label19.setObjectName("label19")
        self.gridLayout_6.addWidget(self.label19, 0, 2, 1, 1)
        self.label19_2 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label19_2.setFont(font)
        self.label19_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label19_2.setObjectName("label19_2")
        self.gridLayout_6.addWidget(self.label19_2, 1, 2, 1, 1)
        self.leExtForceSwitch = QtWidgets.QLineEdit(self.groupBoxExternal)
        self.leExtForceSwitch.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExtForceSwitch.sizePolicy().hasHeightForWidth())
        self.leExtForceSwitch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leExtForceSwitch.setFont(font)
        self.leExtForceSwitch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leExtForceSwitch.setAlignment(QtCore.Qt.AlignCenter)
        self.leExtForceSwitch.setObjectName("leExtForceSwitch")
        self.gridLayout_6.addWidget(self.leExtForceSwitch, 1, 3, 1, 1)
        self.ckbEnbAlarmMode = QtWidgets.QCheckBox(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckbEnbAlarmMode.setFont(font)
        self.ckbEnbAlarmMode.setObjectName("ckbEnbAlarmMode")
        self.gridLayout_6.addWidget(self.ckbEnbAlarmMode, 2, 3, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_6)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.line = QtWidgets.QFrame(self.groupBoxExternal)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_7.setHorizontalSpacing(7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label25 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label25.setFont(font)
        self.label25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label25.setObjectName("label25")
        self.gridLayout_7.addWidget(self.label25, 5, 0, 1, 1)
        self.leExtEccentricInertiaFactor = QtWidgets.QLineEdit(self.groupBoxExternal)
        self.leExtEccentricInertiaFactor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExtEccentricInertiaFactor.sizePolicy().hasHeightForWidth())
        self.leExtEccentricInertiaFactor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leExtEccentricInertiaFactor.setFont(font)
        self.leExtEccentricInertiaFactor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leExtEccentricInertiaFactor.setAlignment(QtCore.Qt.AlignCenter)
        self.leExtEccentricInertiaFactor.setObjectName("leExtEccentricInertiaFactor")
        self.gridLayout_7.addWidget(self.leExtEccentricInertiaFactor, 6, 1, 1, 1)
        self.leExtGravityFactor = QtWidgets.QLineEdit(self.groupBoxExternal)
        self.leExtGravityFactor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExtGravityFactor.sizePolicy().hasHeightForWidth())
        self.leExtGravityFactor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leExtGravityFactor.setFont(font)
        self.leExtGravityFactor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leExtGravityFactor.setAlignment(QtCore.Qt.AlignCenter)
        self.leExtGravityFactor.setObjectName("leExtGravityFactor")
        self.gridLayout_7.addWidget(self.leExtGravityFactor, 0, 1, 1, 1)
        self.label26 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label26.setFont(font)
        self.label26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label26.setObjectName("label26")
        self.gridLayout_7.addWidget(self.label26, 6, 0, 1, 1)
        self.leExtDraggedDynamicFrictionFactor = QtWidgets.QLineEdit(self.groupBoxExternal)
        self.leExtDraggedDynamicFrictionFactor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExtDraggedDynamicFrictionFactor.sizePolicy().hasHeightForWidth())
        self.leExtDraggedDynamicFrictionFactor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leExtDraggedDynamicFrictionFactor.setFont(font)
        self.leExtDraggedDynamicFrictionFactor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leExtDraggedDynamicFrictionFactor.setAlignment(QtCore.Qt.AlignCenter)
        self.leExtDraggedDynamicFrictionFactor.setObjectName("leExtDraggedDynamicFrictionFactor")
        self.gridLayout_7.addWidget(self.leExtDraggedDynamicFrictionFactor, 4, 1, 1, 1)
        self.label22 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label22.setFont(font)
        self.label22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label22.setObjectName("label22")
        self.gridLayout_7.addWidget(self.label22, 2, 0, 1, 1)
        self.leExtConcentricInertiaFactor = QtWidgets.QLineEdit(self.groupBoxExternal)
        self.leExtConcentricInertiaFactor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExtConcentricInertiaFactor.sizePolicy().hasHeightForWidth())
        self.leExtConcentricInertiaFactor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leExtConcentricInertiaFactor.setFont(font)
        self.leExtConcentricInertiaFactor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leExtConcentricInertiaFactor.setAlignment(QtCore.Qt.AlignCenter)
        self.leExtConcentricInertiaFactor.setObjectName("leExtConcentricInertiaFactor")
        self.gridLayout_7.addWidget(self.leExtConcentricInertiaFactor, 5, 1, 1, 1)
        self.leExtDraggedStaticFrictionFactor = QtWidgets.QLineEdit(self.groupBoxExternal)
        self.leExtDraggedStaticFrictionFactor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExtDraggedStaticFrictionFactor.sizePolicy().hasHeightForWidth())
        self.leExtDraggedStaticFrictionFactor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leExtDraggedStaticFrictionFactor.setFont(font)
        self.leExtDraggedStaticFrictionFactor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leExtDraggedStaticFrictionFactor.setAlignment(QtCore.Qt.AlignCenter)
        self.leExtDraggedStaticFrictionFactor.setObjectName("leExtDraggedStaticFrictionFactor")
        self.gridLayout_7.addWidget(self.leExtDraggedStaticFrictionFactor, 3, 1, 1, 1)
        self.label21 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label21.setFont(font)
        self.label21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label21.setObjectName("label21")
        self.gridLayout_7.addWidget(self.label21, 1, 0, 1, 1)
        self.leExtStaticFrictionFactor = QtWidgets.QLineEdit(self.groupBoxExternal)
        self.leExtStaticFrictionFactor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExtStaticFrictionFactor.sizePolicy().hasHeightForWidth())
        self.leExtStaticFrictionFactor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leExtStaticFrictionFactor.setFont(font)
        self.leExtStaticFrictionFactor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leExtStaticFrictionFactor.setAlignment(QtCore.Qt.AlignCenter)
        self.leExtStaticFrictionFactor.setObjectName("leExtStaticFrictionFactor")
        self.gridLayout_7.addWidget(self.leExtStaticFrictionFactor, 1, 1, 1, 1)
        self.leExtDynamicFrictionFactor = QtWidgets.QLineEdit(self.groupBoxExternal)
        self.leExtDynamicFrictionFactor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExtDynamicFrictionFactor.sizePolicy().hasHeightForWidth())
        self.leExtDynamicFrictionFactor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leExtDynamicFrictionFactor.setFont(font)
        self.leExtDynamicFrictionFactor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leExtDynamicFrictionFactor.setAlignment(QtCore.Qt.AlignCenter)
        self.leExtDynamicFrictionFactor.setObjectName("leExtDynamicFrictionFactor")
        self.gridLayout_7.addWidget(self.leExtDynamicFrictionFactor, 2, 1, 1, 1)
        self.label20 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label20.setFont(font)
        self.label20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label20.setObjectName("label20")
        self.gridLayout_7.addWidget(self.label20, 0, 0, 1, 1)
        self.label24 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label24.setFont(font)
        self.label24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label24.setObjectName("label24")
        self.gridLayout_7.addWidget(self.label24, 4, 0, 1, 1)
        self.label23 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label23.setFont(font)
        self.label23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label23.setObjectName("label23")
        self.gridLayout_7.addWidget(self.label23, 3, 0, 1, 1)
        self.leCollisionTestTorque = QtWidgets.QLineEdit(self.groupBoxExternal)
        self.leCollisionTestTorque.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leCollisionTestTorque.sizePolicy().hasHeightForWidth())
        self.leCollisionTestTorque.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leCollisionTestTorque.setFont(font)
        self.leCollisionTestTorque.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leCollisionTestTorque.setAlignment(QtCore.Qt.AlignCenter)
        self.leCollisionTestTorque.setObjectName("leCollisionTestTorque")
        self.gridLayout_7.addWidget(self.leCollisionTestTorque, 0, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 7, 2, 1, 1)
        self.label19_3 = QtWidgets.QLabel(self.groupBoxExternal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label19_3.setFont(font)
        self.label19_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label19_3.setObjectName("label19_3")
        self.gridLayout_7.addWidget(self.label19_3, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_7)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem14)
        self.line_3 = QtWidgets.QFrame(self.groupBoxExternal)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btnReloadMeasuredFactors = QtWidgets.QPushButton(self.groupBoxExternal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnReloadMeasuredFactors.sizePolicy().hasHeightForWidth())
        self.btnReloadMeasuredFactors.setSizePolicy(sizePolicy)
        self.btnReloadMeasuredFactors.setMinimumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnReloadMeasuredFactors.setFont(font)
        self.btnReloadMeasuredFactors.setObjectName("btnReloadMeasuredFactors")
        self.gridLayout_8.addWidget(self.btnReloadMeasuredFactors, 0, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem15, 0, 0, 1, 1)
        self.btnExtForceCompensate = QtWidgets.QPushButton(self.groupBoxExternal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExtForceCompensate.sizePolicy().hasHeightForWidth())
        self.btnExtForceCompensate.setSizePolicy(sizePolicy)
        self.btnExtForceCompensate.setMinimumSize(QtCore.QSize(150, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnExtForceCompensate.setFont(font)
        self.btnExtForceCompensate.setObjectName("btnExtForceCompensate")
        self.gridLayout_8.addWidget(self.btnExtForceCompensate, 1, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_8)
        self.verticalLayout_4.addWidget(self.groupBoxExternal)
        self.tbwMotionTuner.addTab(self.extForceCompensation, "")
        self.ConfigManagement = QtWidgets.QWidget()
        self.ConfigManagement.setObjectName("ConfigManagement")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ConfigManagement)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBoxExternal_2 = QtWidgets.QGroupBox(self.ConfigManagement)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBoxExternal_2.setFont(font)
        self.groupBoxExternal_2.setObjectName("groupBoxExternal_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBoxExternal_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.btnSaveMotionConfigFile = QtWidgets.QPushButton(self.groupBoxExternal_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveMotionConfigFile.sizePolicy().hasHeightForWidth())
        self.btnSaveMotionConfigFile.setSizePolicy(sizePolicy)
        self.btnSaveMotionConfigFile.setMinimumSize(QtCore.QSize(150, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnSaveMotionConfigFile.setFont(font)
        self.btnSaveMotionConfigFile.setObjectName("btnSaveMotionConfigFile")
        self.gridLayout_11.addWidget(self.btnSaveMotionConfigFile, 1, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem16, 3, 1, 1, 1)
        self.btnLoadMotionConfigFile = QtWidgets.QPushButton(self.groupBoxExternal_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadMotionConfigFile.sizePolicy().hasHeightForWidth())
        self.btnLoadMotionConfigFile.setSizePolicy(sizePolicy)
        self.btnLoadMotionConfigFile.setMinimumSize(QtCore.QSize(150, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnLoadMotionConfigFile.setFont(font)
        self.btnLoadMotionConfigFile.setObjectName("btnLoadMotionConfigFile")
        self.gridLayout_11.addWidget(self.btnLoadMotionConfigFile, 0, 2, 1, 1)
        self.leMotionConfigFilePath = QtWidgets.QLineEdit(self.groupBoxExternal_2)
        self.leMotionConfigFilePath.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leMotionConfigFilePath.sizePolicy().hasHeightForWidth())
        self.leMotionConfigFilePath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.leMotionConfigFilePath.setFont(font)
        self.leMotionConfigFilePath.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leMotionConfigFilePath.setText("")
        self.leMotionConfigFilePath.setAlignment(QtCore.Qt.AlignCenter)
        self.leMotionConfigFilePath.setObjectName("leMotionConfigFilePath")
        self.gridLayout_11.addWidget(self.leMotionConfigFilePath, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_11)
        spacerItem17 = QtWidgets.QSpacerItem(17, 139, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem17)
        self.verticalLayout_6.addWidget(self.groupBoxExternal_2)
        self.tbwMotionTuner.addTab(self.ConfigManagement, "")
        self.verticalLayout.addWidget(self.tbwMotionTuner)

        self.retranslateUi(Form)
        self.tbwMotionTuner.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Motion Tuner"))
        self.groupBoxGravityCalculate.setTitle(_translate("Form", "Gravity Distribution Calculation"))
        self.label7.setText(_translate("Form", "Tool weight (kg) :"))
        self.btnGravityDistribution.setText(_translate("Form", "Start"))
        self.leToolWeight.setText(_translate("Form", "0"))
        self.groupBoxGravityAdjustment.setTitle(_translate("Form", "Gravity Factor Measurement Condition"))
        self.btnGravityFactorMeasure.setText(_translate("Form", "Start"))
        self.label8.setText(_translate("Form", "Axis :"))
        self.label9.setText(_translate("Form", "Angle (deg) :"))
        self.label10.setText(_translate("Form", "Sampling Time(ms) :"))
        self.leGravitySamplingTime.setText(_translate("Form", "0"))
        self.label11_3.setText(_translate("Form", "Initial Gravity Factor :"))
        self.leGravityInitialFactor.setText(_translate("Form", "0"))
        self.label11_2.setText(_translate("Form", "Speed Limit(0.1deg/s) :"))
        self.leGravitySpeedLimit.setText(_translate("Form", "0"))
        self.label11.setText(_translate("Form", "Speed(0.1deg/s) :"))
        self.leGravitySpeed.setText(_translate("Form", "0"))
        self.groupBoxGravityAdjustment_2.setTitle(_translate("Form", "Test Result"))
        self.label14.setText(_translate("Form", "Average Torque:"))
        self.label13.setText(_translate("Form", "Average Gravity:"))
        self.leSampledPoints.setText(_translate("Form", "0"))
        self.leAverageGravity.setText(_translate("Form", "0"))
        self.leAverageTorque.setText(_translate("Form", "0"))
        self.leGravityFactor.setText(_translate("Form", "0"))
        self.label12.setText(_translate("Form", "Gravity Factor:"))
        self.label15.setText(_translate("Form", "Sampled Points:"))
        self.tbwMotionTuner.setTabText(self.tbwMotionTuner.indexOf(self.GravityFactor), _translate("Form", "Gravity Factor"))
        self.groupBoxFriction.setTitle(_translate("Form", "Friction Factor Measurement Condition"))
        self.label_5.setText(_translate("Form", "Angle (deg) :"))
        self.leFrictionMaxTestSpeed.setText(_translate("Form", "0"))
        self.leFrictionMinTestSpeed.setText(_translate("Form", "0"))
        self.label_10.setText(_translate("Form", "Max. Test Speed(0.1deg/s) :"))
        self.leFrictionSpeedTestSections.setText(_translate("Form", "0"))
        self.label_8.setText(_translate("Form", "Speed Limit(0.1deg/s) :"))
        self.label_6.setText(_translate("Form", "Axis :"))
        self.label_9.setText(_translate("Form", "Min. Test Speed(0.1deg/s) :"))
        self.label_11.setText(_translate("Form", "Speed Test Sections :"))
        self.leFrictionSpeedLimit.setText(_translate("Form", "0"))
        self.label_7.setText(_translate("Form", "Sampling Time(ms) :"))
        self.leFrictionSamplingTime.setText(_translate("Form", "0"))
        self.btnFrictionFactorMeasure.setText(_translate("Form", "Start"))
        self.groupBox.setTitle(_translate("Form", "Test Result"))
        self.label.setText(_translate("Form", "Static Friction Factor :"))
        self.leDynamicFriction.setText(_translate("Form", "0"))
        self.label_2.setText(_translate("Form", "Dynamic Friction Factor :"))
        self.label_3.setText(_translate("Form", "Dragged Static Friction Factor :"))
        self.leDraggedStaticFriction.setText(_translate("Form", "0"))
        self.label_4.setText(_translate("Form", " Dragged Dynamic Friction Factor :"))
        self.leDraggedDynamicFriction.setText(_translate("Form", "0"))
        self.leStaticFriction.setText(_translate("Form", "0"))
        self.tbwMotionTuner.setTabText(self.tbwMotionTuner.indexOf(self.FrictionFactor), _translate("Form", "Friction Factor"))
        self.groupBoxExternal.setTitle(_translate("Form", "extForce Compensation Test"))
        self.label17.setText(_translate("Form", "Angle (deg) :"))
        self.leExtSamplingTime.setText(_translate("Form", "0"))
        self.label18_2.setText(_translate("Form", "Sampling Time(ms) :"))
        self.label16.setText(_translate("Form", "Axis :"))
        self.leExtSpeed.setText(_translate("Form", "0"))
        self.label18.setText(_translate("Form", "Speed(0.1deg/s) :"))
        self.leExtDecelerationLimit.setText(_translate("Form", "0"))
        self.label19.setText(_translate("Form", "Deceleration Limit :"))
        self.label19_2.setText(_translate("Form", "extForce Switch(extMXC) :"))
        self.leExtForceSwitch.setText(_translate("Form", "0"))
        self.ckbEnbAlarmMode.setText(_translate("Form", "Enable Alarm Mode"))
        self.label25.setText(_translate("Form", "Concentric Inertia Factor(extKM) :"))
        self.leExtEccentricInertiaFactor.setText(_translate("Form", "0"))
        self.leExtGravityFactor.setText(_translate("Form", "0"))
        self.label26.setText(_translate("Form", "Eccentric Inertia Factor(extKA) :"))
        self.leExtDraggedDynamicFrictionFactor.setText(_translate("Form", "0"))
        self.label22.setText(_translate("Form", "Dynamic Friction Factor(extKV) :"))
        self.leExtConcentricInertiaFactor.setText(_translate("Form", "0"))
        self.leExtDraggedStaticFrictionFactor.setText(_translate("Form", "0"))
        self.label21.setText(_translate("Form", "Static Friction Factor(extKV0) :"))
        self.leExtStaticFrictionFactor.setText(_translate("Form", "0"))
        self.leExtDynamicFrictionFactor.setText(_translate("Form", "0"))
        self.label20.setText(_translate("Form", "Gravity Factor(extKG):"))
        self.label24.setText(_translate("Form", "Dragged Dynamic Friction Factor(extKS) :"))
        self.label23.setText(_translate("Form", "Dragged Static Friction Factor(extKS0) :"))
        self.leCollisionTestTorque.setText(_translate("Form", "0"))
        self.label19_3.setText(_translate("Form", "Collision Test Torque(drvTRQ) :"))
        self.btnReloadMeasuredFactors.setText(_translate("Form", "Reload Measured Factors"))
        self.btnExtForceCompensate.setText(_translate("Form", "Start"))
        self.tbwMotionTuner.setTabText(self.tbwMotionTuner.indexOf(self.extForceCompensation), _translate("Form", "extForce Compensation"))
        self.groupBoxExternal_2.setTitle(_translate("Form", "Config File for Tuner"))
        self.btnSaveMotionConfigFile.setText(_translate("Form", "Save"))
        self.btnLoadMotionConfigFile.setText(_translate("Form", "Load"))
        self.tbwMotionTuner.setTabText(self.tbwMotionTuner.indexOf(self.ConfigManagement), _translate("Form", "Config Management"))
