# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/frmStartUp.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(822, 314)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMinimumSize(QtCore.QSize(800, 0))
        self.groupBox.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(355, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.btnCommControl = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCommControl.sizePolicy().hasHeightForWidth())
        self.btnCommControl.setSizePolicy(sizePolicy)
        self.btnCommControl.setMinimumSize(QtCore.QSize(170, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnCommControl.setFont(font)
        self.btnCommControl.setObjectName("btnCommControl")
        self.gridLayout.addWidget(self.btnCommControl, 0, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ckbSimuEnable = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckbSimuEnable.setFont(font)
        self.ckbSimuEnable.setObjectName("ckbSimuEnable")
        self.verticalLayout_2.addWidget(self.ckbSimuEnable)
        self.cboSerialPortSelector = QtWidgets.QComboBox(self.groupBox)
        self.cboSerialPortSelector.setMinimumSize(QtCore.QSize(251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cboSerialPortSelector.setFont(font)
        self.cboSerialPortSelector.setObjectName("cboSerialPortSelector")
        self.verticalLayout_2.addWidget(self.cboSerialPortSelector)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(-1, 11, -1, -1)
        self.gridLayout_2.setVerticalSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ckbCreate3dModel = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckbCreate3dModel.setFont(font)
        self.ckbCreate3dModel.setObjectName("ckbCreate3dModel")
        self.verticalLayout_3.addWidget(self.ckbCreate3dModel)
        self.ckbEnbExtForceMode = QtWidgets.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ckbEnbExtForceMode.setFont(font)
        self.ckbEnbExtForceMode.setObjectName("ckbEnbExtForceMode")
        self.verticalLayout_3.addWidget(self.ckbEnbExtForceMode)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cboJ3AngLimitation = QtWidgets.QComboBox(self.groupBox_2)
        self.cboJ3AngLimitation.setMinimumSize(QtCore.QSize(141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cboJ3AngLimitation.setFont(font)
        self.cboJ3AngLimitation.setObjectName("cboJ3AngLimitation")
        self.horizontalLayout_2.addWidget(self.cboJ3AngLimitation)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(317, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.btnServoControl = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnServoControl.sizePolicy().hasHeightForWidth())
        self.btnServoControl.setSizePolicy(sizePolicy)
        self.btnServoControl.setMinimumSize(QtCore.QSize(170, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnServoControl.setFont(font)
        self.btnServoControl.setObjectName("btnServoControl")
        self.gridLayout_2.addWidget(self.btnServoControl, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Communication"))
        self.btnCommControl.setText(_translate("Form", "Connect"))
        self.ckbSimuEnable.setText(_translate("Form", "Simulation Enable"))
        self.groupBox_2.setTitle(_translate("Form", "Servo Control"))
        self.ckbCreate3dModel.setText(_translate("Form", "Create 3D Model"))
        self.ckbEnbExtForceMode.setText(_translate("Form", "Enable Cobot Mode (extForce Mode)"))
        self.label.setText(_translate("Form", "Joint-3 Angle Limitation:"))
        self.btnServoControl.setText(_translate("Form", "Servo ON"))
