# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/frmScriptEditor.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(803, 741)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tblScriptEditor = QtWidgets.QTableWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tblScriptEditor.setFont(font)
        self.tblScriptEditor.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
        self.tblScriptEditor.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tblScriptEditor.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblScriptEditor.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblScriptEditor.setShowGrid(False)
        self.tblScriptEditor.setGridStyle(QtCore.Qt.NoPen)
        self.tblScriptEditor.setWordWrap(False)
        self.tblScriptEditor.setCornerButtonEnabled(False)
        self.tblScriptEditor.setObjectName("tblScriptEditor")
        self.tblScriptEditor.setColumnCount(1)
        self.tblScriptEditor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblScriptEditor.setHorizontalHeaderItem(0, item)
        self.tblScriptEditor.horizontalHeader().setStretchLastSection(True)
        self.tblScriptEditor.verticalHeader().setVisible(True)
        self.horizontalLayout.addWidget(self.tblScriptEditor)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 80, -1, -1)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnCompile = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCompile.sizePolicy().hasHeightForWidth())
        self.btnCompile.setSizePolicy(sizePolicy)
        self.btnCompile.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnCompile.setFont(font)
        self.btnCompile.setObjectName("btnCompile")
        self.verticalLayout.addWidget(self.btnCompile)
        self.btnRun = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRun.sizePolicy().hasHeightForWidth())
        self.btnRun.setSizePolicy(sizePolicy)
        self.btnRun.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnRun.setFont(font)
        self.btnRun.setObjectName("btnRun")
        self.verticalLayout.addWidget(self.btnRun)
        self.btnRemoveLine = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemoveLine.sizePolicy().hasHeightForWidth())
        self.btnRemoveLine.setSizePolicy(sizePolicy)
        self.btnRemoveLine.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnRemoveLine.setFont(font)
        self.btnRemoveLine.setObjectName("btnRemoveLine")
        self.verticalLayout.addWidget(self.btnRemoveLine)
        self.btnClearAll = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClearAll.sizePolicy().hasHeightForWidth())
        self.btnClearAll.setSizePolicy(sizePolicy)
        self.btnClearAll.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnClearAll.setFont(font)
        self.btnClearAll.setObjectName("btnClearAll")
        self.verticalLayout.addWidget(self.btnClearAll)
        self.btnLoadScriptFromFile = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadScriptFromFile.sizePolicy().hasHeightForWidth())
        self.btnLoadScriptFromFile.setSizePolicy(sizePolicy)
        self.btnLoadScriptFromFile.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnLoadScriptFromFile.setFont(font)
        self.btnLoadScriptFromFile.setObjectName("btnLoadScriptFromFile")
        self.verticalLayout.addWidget(self.btnLoadScriptFromFile)
        self.btnSaveScriptToFile = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveScriptToFile.sizePolicy().hasHeightForWidth())
        self.btnSaveScriptToFile.setSizePolicy(sizePolicy)
        self.btnSaveScriptToFile.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnSaveScriptToFile.setFont(font)
        self.btnSaveScriptToFile.setObjectName("btnSaveScriptToFile")
        self.verticalLayout.addWidget(self.btnSaveScriptToFile)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cboDefaultSpeed = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboDefaultSpeed.sizePolicy().hasHeightForWidth())
        self.cboDefaultSpeed.setSizePolicy(sizePolicy)
        self.cboDefaultSpeed.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cboDefaultSpeed.setFont(font)
        self.cboDefaultSpeed.setObjectName("cboDefaultSpeed")
        self.horizontalLayout_2.addWidget(self.cboDefaultSpeed)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tblScriptEditor.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Command"))
        self.btnCompile.setText(_translate("Form", "Compile"))
        self.btnRun.setText(_translate("Form", "Run"))
        self.btnRemoveLine.setText(_translate("Form", "Remove Line"))
        self.btnClearAll.setText(_translate("Form", "Clear All"))
        self.btnLoadScriptFromFile.setText(_translate("Form", "Load Script From File"))
        self.btnSaveScriptToFile.setText(_translate("Form", "Save Script To File"))
        self.label.setText(_translate("Form", "Def.Speed:"))
